// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEu-HXgpZwVYOzjkvUsZ7UtK_yoLn_rBA',
    appId: '1:916226322134:web:25abcca8200d76c965e377',
    messagingSenderId: '916226322134',
    projectId: 'mynotes8h8',
    authDomain: 'mynotes8h8.firebaseapp.com',
    storageBucket: 'mynotes8h8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFF7LooFNdNtqB6fIVnw2vmAHtA7ZvzV4',
    appId: '1:916226322134:android:9934c0f88cb3a14065e377',
    messagingSenderId: '916226322134',
    projectId: 'mynotes8h8',
    storageBucket: 'mynotes8h8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4vOdj4ahlHdXtl2xF_KrZ__9X6zSEVA',
    appId: '1:916226322134:ios:514b0f35997048a465e377',
    messagingSenderId: '916226322134',
    projectId: 'mynotes8h8',
    storageBucket: 'mynotes8h8.firebasestorage.app',
    iosBundleId: 'com.keeptracks.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4vOdj4ahlHdXtl2xF_KrZ__9X6zSEVA',
    appId: '1:916226322134:ios:514b0f35997048a465e377',
    messagingSenderId: '916226322134',
    projectId: 'mynotes8h8',
    storageBucket: 'mynotes8h8.firebasestorage.app',
    iosBundleId: 'com.keeptracks.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEu-HXgpZwVYOzjkvUsZ7UtK_yoLn_rBA',
    appId: '1:916226322134:web:adf3b30d74e25d6d65e377',
    messagingSenderId: '916226322134',
    projectId: 'mynotes8h8',
    authDomain: 'mynotes8h8.firebaseapp.com',
    storageBucket: 'mynotes8h8.firebasestorage.app',
  );
}
